/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e0df85adc796a7375f8bd4eb9a04b707)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSET_BASE_URL: "https://assets.ludusales.com";
	RESEND_API_KEY: string;
	CONTACT_TO_EMAIL: string;
	RESEND_FROM_EMAIL: string;
	FRONTEND_ORIGINS: string;
	JWT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSET_BASE_URL" | "RESEND_API_KEY" | "CONTACT_TO_EMAIL" | "RESEND_FROM_EMAIL" | "FRONTEND_ORIGINS" | "JWT_SECRET">> {}
}
