/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 29b36677f5cb0cd928c482a7b9632bc7)
interface __BaseEnv_Env {
	DB: D1Database;
	RESEND_API_KEY: string;
	CONTACT_TO_EMAIL: string;
	RESEND_FROM_EMAIL: string;
	FRONTEND_ORIGINS: string;
	JWT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
